In [1]:
import torch
from torch import nn

In [2]:
# arange产生（start，end）之间的整数，默认从0开始到end
data = torch.arange(12,dtype=float).reshape(4,3)
data

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

# SoftMax
softmax是对某个纬度的所有值转换到(0,1),该维度所有转换后的值和为1

In [3]:
# dim (-2,1)
SM = nn.Softmax(1)

In [4]:
result = SM(data)
result, result.shape

(tensor([[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]], dtype=torch.float64),
 torch.Size([4, 3]))

In [5]:
data = data.reshape(2,2,3)
data

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=torch.float64)

In [6]:
SM_1 = nn.Softmax(0)

In [7]:
result_1 = SM_1(data)
result_1, result_1.shape

(tensor([[[0.0025, 0.0025, 0.0025],
          [0.0025, 0.0025, 0.0025]],
 
         [[0.9975, 0.9975, 0.9975],
          [0.9975, 0.9975, 0.9975]]], dtype=torch.float64),
 torch.Size([2, 2, 3]))